### ISSUE TITLE
Low accuracy

### ISSUE THREAD

**Issue by sabrinazuraimi** [Goldesel23/Siamese-Networks-for-One-Shot-Learning#2] opened 2018-08-14 15:35 UTC
Hi, i cloned the repo and tried running it as it is but my accuracy doesn't seem to be improving. Is it because of the TensorFlow warning that I get? Is there any pre-processing that I'm supposed to do before running the train_siamese_networks

> (mypython3) MacBook-Pro-3:one-shot Sabrinai$ python train_siamese_network.py
> Using TensorFlow backend.
> 2018-08-14 18:21:16.735624: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> Iteration 1/1000000: Train loss: 4.849324, Train Accuracy: 0.531250, lr = 0.001000
> Iteration 2/1000000: Train loss: 4.848513, Train Accuracy: 0.453125, lr = 0.001000
> Iteration 3/1000000: Train loss: 4.848382, Train Accuracy: 0.515625, lr = 0.001000
> Iteration 4/1000000: Train loss: 4.848629, Train Accuracy: 0.546875, lr = 0.001000
> Iteration 5/1000000: Train loss: 4.848142, Train Accuracy: 0.578125, lr = 0.001000
> Iteration 6/1000000: Train loss: 4.848841, Train Accuracy: 0.468750, lr = 0.001000
> Iteration 7/1000000: Train loss: 4.846568, Train Accuracy: 0.578125, lr = 0.001000
> Iteration 8/1000000: Train loss: 4.847251, Train Accuracy: 0.484375, lr = 0.001000
> Iteration 9/1000000: Train loss: 4.846010, Train Accuracy: 0.578125, lr = 0.001000
> Iteration 10/1000000: Train loss: 4.846083, Train Accuracy: 0.562500, lr = 0.001000
> Iteration 11/1000000: Train loss: 4.846534, Train Accuracy: 0.437500, lr = 0.001000
> Iteration 12/1000000: Train loss: 4.846575, Train Accuracy: 0.484375, lr = 0.001000
> Iteration 13/1000000: Train loss: 4.846043, Train Accuracy: 0.468750, lr = 0.001000
> Iteration 14/1000000: Train loss: 4.844590, Train Accuracy: 0.609375, lr = 0.001000
> Iteration 15/1000000: Train loss: 4.844895, Train Accuracy: 0.468750, lr = 0.001000
> Iteration 16/1000000: Train loss: 4.844888, Train Accuracy: 0.468750, lr = 0.001000
> Iteration 17/1000000: Train loss: 4.845278, Train Accuracy: 0.484375, lr = 0.001000
> Iteration 18/1000000: Train loss: 4.843062, Train Accuracy: 0.562500, lr = 0.001000
> Iteration 19/1000000: Train loss: 4.843076, Train Accuracy: 0.593750, lr = 0.001000
> Iteration 20/1000000: Train loss: 4.842909, Train Accuracy: 0.437500, lr = 0.001000
> Iteration 21/1000000: Train loss: 4.842513, Train Accuracy: 0.531250, lr = 0.001000
> Iteration 22/1000000: Train loss: 4.841990, Train Accuracy: 0.484375, lr = 0.001000
> Iteration 23/1000000: Train loss: 4.841151, Train Accuracy: 0.500000, lr = 0.001000
> Iteration 24/1000000: Train loss: 4.841326, Train Accuracy: 0.500000, lr = 0.001000
> Iteration 25/1000000: Train loss: 4.840984, Train Accuracy: 0.437500, lr = 0.001000
> Iteration 26/1000000: Train loss: 4.838634, Train Accuracy: 0.515625, lr = 0.001000
> Iteration 27/1000000: Train loss: 4.838871, Train Accuracy: 0.609375, lr = 0.001000
> Iteration 28/1000000: Train loss: 4.837312, Train Accuracy: 0.609375, lr = 0.001000
> Iteration 29/1000000: Train loss: 4.838040, Train Accuracy: 0.578125, lr = 0.001000
> Iteration 30/1000000: Train loss: 4.836654, Train Accuracy: 0.531250, lr = 0.001000
> Iteration 31/1000000: Train loss: 4.835261, Train Accuracy: 0.578125, lr = 0.001000
> Iteration 32/1000000: Train loss: 4.836050, Train Accuracy: 0.515625, lr = 0.001000
> Iteration 33/1000000: Train loss: 4.835767, Train Accuracy: 0.515625, lr = 0.001000
> Iteration 34/1000000: Train loss: 4.834557, Train Accuracy: 0.500000, lr = 0.001000
> Iteration 35/1000000: Train loss: 4.833904, Train Accuracy: 0.500000, lr = 0.001000
> Iteration 36/1000000: Train loss: 4.832893, Train Accuracy: 0.515625, lr = 0.001000
> Iteration 37/1000000: Train loss: 4.832811, Train Accuracy: 0.453125, lr = 0.001000
> Iteration 38/1000000: Train loss: 4.829530, Train Accuracy: 0.625000, lr = 0.001000
> Iteration 39/1000000: Train loss: 4.830757, Train Accuracy: 0.421875, lr = 0.001000
> Iteration 40/1000000: Train loss: 4.829597, Train Accuracy: 0.468750, lr = 0.001000
> Iteration 41/1000000: Train loss: 4.830768, Train Accuracy: 0.531250, lr = 0.001000
> Iteration 42/1000000: Train loss: 4.826791, Train Accuracy: 0.515625, lr = 0.001000
> Iteration 43/1000000: Train loss: 4.825655, Train Accuracy: 0.578125, lr = 0.001000
> Iteration 44/1000000: Train loss: 4.825454, Train Accuracy: 0.562500, lr = 0.001000
> Iteration 45/1000000: Train loss: 4.823873, Train Accuracy: 0.578125, lr = 0.001000
> Iteration 46/1000000: Train loss: 4.821697, Train Accuracy: 0.531250, lr = 0.001000
> Iteration 47/1000000: Train loss: 4.821634, Train Accuracy: 0.546875, lr = 0.001000
> Iteration 48/1000000: Train loss: 4.819137, Train Accuracy: 0.593750, lr = 0.001000
> Iteration 49/1000000: Train loss: 4.818835, Train Accuracy: 0.531250, lr = 0.001000
> Iteration 50/1000000: Train loss: 4.813269, Train Accuracy: 0.468750, lr = 0.001000
> Iteration 51/1000000: Train loss: 4.813827, Train Accuracy: 0.562500, lr = 0.001000
> Iteration 52/1000000: Train loss: 4.813818, Train Accuracy: 0.500000, lr = 0.001000
> Iteration 53/1000000: Train loss: 4.813799, Train Accuracy: 0.437500, lr = 0.001000
> Iteration 54/1000000: Train loss: 4.810773, Train Accuracy: 0.515625, lr = 0.001000
> Iteration 55/1000000: Train loss: 4.808959, Train Accuracy: 0.500000, lr = 0.001000
> Iteration 56/1000000: Train loss: 4.810541, Train Accuracy: 0.453125, lr = 0.001000
> Iteration 57/1000000: Train loss: 4.807623, Train Accuracy: 0.453125, lr = 0.001000
> Iteration 58/1000000: Train loss: 4.804411, Train Accuracy: 0.531250, lr = 0.001000
> Iteration 59/1000000: Train loss: 4.800980, Train Accuracy: 0.546875, lr = 0.001000
> Iteration 60/1000000: Train loss: 4.802567, Train Accuracy: 0.484375, lr = 0.001000
> Iteration 61/1000000: Train loss: 4.801285, Train Accuracy: 0.468750, lr = 0.001000
> Iteration 62/1000000: Train loss: 4.798449, Train Accuracy: 0.453125, lr = 0.001000
> Iteration 63/1000000: Train loss: 4.795244, Train Accuracy: 0.515625, lr = 0.001000
> Iteration 64/1000000: Train loss: 4.795055, Train Accuracy: 0.468750, lr = 0.001000
> Iteration 65/1000000: Train loss: 4.790056, Train Accuracy: 0.500000, lr = 0.001000
> Iteration 66/1000000: Train loss: 4.792620, Train Accuracy: 0.515625, lr = 0.001000
> Iteration 67/1000000: Train loss: 4.791032, Train Accuracy: 0.468750, lr = 0.001000
> Iteration 68/1000000: Train loss: 4.788491, Train Accuracy: 0.515625, lr = 0.001000
> Iteration 69/1000000: Train loss: 4.787354, Train Accuracy: 0.500000, lr = 0.001000
> Iteration 70/1000000: Train loss: 4.785830, Train Accuracy: 0.484375, lr = 0.001000
> Iteration 71/1000000: Train loss: 4.783831, Train Accuracy: 0.484375, lr = 0.001000
> Iteration 72/1000000: Train loss: 4.781487, Train Accuracy: 0.500000, lr = 0.001000
> Iteration 73/1000000: Train loss: 4.779665, Train Accuracy: 0.546875, lr = 0.001000
> Iteration 74/1000000: Train loss: 4.779678, Train Accuracy: 0.500000, lr = 0.001000
> Iteration 75/1000000: Train loss: 4.777548, Train Accuracy: 0.484375, lr = 0.001000
> Iteration 76/1000000: Train loss: 4.774950, Train Accuracy: 0.515625, lr = 0.001000
> Iteration 77/1000000: Train loss: 4.774406, Train Accuracy: 0.437500, lr = 0.001000
> Iteration 78/1000000: Train loss: 4.768193, Train Accuracy: 0.515625, lr = 0.001000
> Iteration 79/1000000: Train loss: 4.769056, Train Accuracy: 0.500000, lr = 0.001000
> Iteration 80/1000000: Train loss: 4.764924, Train Accuracy: 0.546875, lr = 0.001000
> Iteration 81/1000000: Train loss: 4.766854, Train Accuracy: 0.500000, lr = 0.001000
> Iteration 82/1000000: Train loss: 4.763232, Train Accuracy: 0.515625, lr = 0.001000
> Iteration 83/1000000: Train loss: 4.761155, Train Accuracy: 0.531250, lr = 0.001000
> Iteration 84/1000000: Train loss: 4.760967, Train Accuracy: 0.484375, lr = 0.001000
> Iteration 85/1000000: Train loss: 4.758671, Train Accuracy: 0.562500, lr = 0.001000
> Iteration 86/1000000: Train loss: 4.754441, Train Accuracy: 0.562500, lr = 0.001000
> Iteration 87/1000000: Train loss: 4.756378, Train Accuracy: 0.500000, lr = 0.001000
> Iteration 88/1000000: Train loss: 4.754009, Train Accuracy: 0.531250, lr = 0.001000
> Iteration 89/1000000: Train loss: 4.769855, Train Accuracy: 0.515625, lr = 0.001000
> Iteration 90/1000000: Train loss: 4.751012, Train Accuracy: 0.546875, lr = 0.001000
> Iteration 91/1000000: Train loss: 4.749597, Train Accuracy: 0.562500, lr = 0.001000
> Iteration 92/1000000: Train loss: 4.745842, Train Accuracy: 0.515625, lr = 0.001000
> Iteration 93/1000000: Train loss: 4.747173, Train Accuracy: 0.484375, lr = 0.001000
> Iteration 94/1000000: Train loss: 4.744622, Train Accuracy: 0.546875, lr = 0.001000
> Iteration 95/1000000: Train loss: 4.743729, Train Accuracy: 0.484375, lr = 0.001000
> Iteration 96/1000000: Train loss: 4.740994, Train Accuracy: 0.531250, lr = 0.001000
> Iteration 97/1000000: Train loss: 4.739508, Train Accuracy: 0.531250, lr = 0.001000
> Iteration 98/1000000: Train loss: 4.727015, Train Accuracy: 0.515625, lr = 0.001000
> Iteration 99/1000000: Train loss: 4.733810, Train Accuracy: 0.578125, lr = 0.001000
>

**Comment by tensorfreitas** [comment] 2018-08-14 15:47
Are you running the exact same code? 

The loss is decreasing, so you just need to give it some time I guess. The preprocessing is already implemented in the code. 

Each 1000 batch iterations you get the results on the validations alphabets. Just let the code run for some thousand iterations and visualize the Tensorboard logs. 

PS: The warning is normal, it just means you din't compiled TensorFlow with optimizations (for example if you directly installed from pip).

**Comment by sabrinazuraimi** [comment] 2018-08-16 03:08
I'm running this on the CPU so it's taking a while but I do see improvements in the accuracy


> Iteration 4479/1000000: Train loss: 1.452929, Train Accuracy: 0.687500, lr = 0.000923
> Iteration 4480/1000000: Train loss: 1.450906, Train Accuracy: 0.640625, lr = 0.000923
> Iteration 4481/1000000: Train loss: 1.433053, Train Accuracy: 0.703125, lr = 0.000923
> Iteration 4482/1000000: Train loss: 1.727134, Train Accuracy: 0.500000, lr = 0.000923
> Iteration 4483/1000000: Train loss: 1.459858, Train Accuracy: 0.625000, lr = 0.000923
> Iteration 4484/1000000: Train loss: 1.419593, Train Accuracy: 0.750000, lr = 0.000923
> Iteration 4485/1000000: Train loss: 1.465425, Train Accuracy: 0.671875, lr = 0.000923
> Iteration 4486/1000000: Train loss: 1.417213, Train Accuracy: 0.781250, lr = 0.000923
> Iteration 4487/1000000: Train loss: 1.495863, Train Accuracy: 0.640625, lr = 0.000923
> Iteration 4488/1000000: Train loss: 1.403951, Train Accuracy: 0.828125, lr = 0.000923
> Iteration 4489/1000000: Train loss: 1.457087, Train Accuracy: 0.750000, lr = 0.000923
> Iteration 4490/1000000: Train loss: 1.429594, Train Accuracy: 0.734375, lr = 0.000923
> Iteration 4491/1000000: Train loss: 1.439949, Train Accuracy: 0.687500, lr = 0.000923
> Iteration 4492/1000000: Train loss: 1.446236, Train Accuracy: 0.703125, lr = 0.000923
> Iteration 4493/1000000: Train loss: 1.422630, Train Accuracy: 0.671875, lr = 0.000923
> Iteration 4494/1000000: Train loss: 1.400056, Train Accuracy: 0.687500, lr = 0.000923
> Iteration 4495/1000000: Train loss: 1.390792, Train Accuracy: 0.750000, lr = 0.000923
> Iteration 4496/1000000: Train loss: 1.366196, Train Accuracy: 0.812500, lr = 0.000923
> Iteration 4497/1000000: Train loss: 1.439356, Train Accuracy: 0.718750, lr = 0.000923
> Iteration 4498/1000000: Train loss: 1.454048, Train Accuracy: 0.671875, lr = 0.000923
> Iteration 4499/1000000: Train loss: 1.498700, Train Accuracy: 0.625000, lr = 0.000923
> Iteration 4500/1000000: Train loss: 1.475772, Train Accuracy: 0.640625, lr = 0.000914
> Iteration 4501/1000000: Train loss: 1.402184, Train Accuracy: 0.734375, lr = 0.000914
> Iteration 4502/1000000: Train loss: 1.461725, Train Accuracy: 0.687500, lr = 0.000914
> Iteration 4503/1000000: Train loss: 1.396478, Train Accuracy: 0.750000, lr = 0.000914
> Iteration 4504/1000000: Train loss: 1.376715, Train Accuracy: 0.750000, lr = 0.000914
> Iteration 4505/1000000: Train loss: 1.469028, Train Accuracy: 0.687500, lr = 0.000914
> Iteration 4506/1000000: Train loss: 1.768929, Train Accuracy: 0.500000, lr = 0.000914
> Iteration 4507/1000000: Train loss: 1.432598, Train Accuracy: 0.750000, lr = 0.000914
> Iteration 4508/1000000: Train loss: 1.485716, Train Accuracy: 0.625000, lr = 0.000914
> Iteration 4509/1000000: Train loss: 1.441168, Train Accuracy: 0.656250, lr = 0.000914
> Iteration 4510/1000000: Train loss: 1.407890, Train Accuracy: 0.703125, lr = 0.000914
> Iteration 4511/1000000: Train loss: 1.476840, Train Accuracy: 0.656250, lr = 0.000914
> Iteration 4512/1000000: Train loss: 1.417814, Train Accuracy: 0.718750, lr = 0.000914
> Iteration 4513/1000000: Train loss: 1.453062, Train Accuracy: 0.671875, lr = 0.000914
> Iteration 4514/1000000: Train loss: 1.425027, Train Accuracy: 0.718750, lr = 0.000914
> Iteration 4515/1000000: Train loss: 1.395687, Train Accuracy: 0.750000, lr = 0.000914
> Iteration 4516/1000000: Train loss: 1.474755, Train Accuracy: 0.703125, lr = 0.000914
> Iteration 4517/1000000: Train loss: 1.426591, Train Accuracy: 0.703125, lr = 0.000914
> Iteration 4518/1000000: Train loss: 1.429635, Train Accuracy: 0.765625, lr = 0.000914
> Iteration 4519/1000000: Train loss: 1.418274, Train Accuracy: 0.656250, lr = 0.000914
> Iteration 4520/1000000: Train loss: 1.370978, Train Accuracy: 0.734375, lr = 0.000914
> Iteration 4521/1000000: Train loss: 1.465112, Train Accuracy: 0.671875, lr = 0.000914
> Iteration 4522/1000000: Train loss: 1.442870, Train Accuracy: 0.703125, lr = 0.000914
> Iteration 4523/1000000: Train loss: 1.452683, Train Accuracy: 0.625000, lr = 0.000914
> Iteration 4524/1000000: Train loss: 1.412523, Train Accuracy: 0.734375, lr = 0.000914
> Iteration 4525/1000000: Train loss: 1.442084, Train Accuracy: 0.656250, lr = 0.000914
> Iteration 4526/1000000: Train loss: 1.520849, Train Accuracy: 0.625000, lr = 0.000914
> Iteration 4527/1000000: Train loss: 1.461538, Train Accuracy: 0.578125, lr = 0.000914
> Iteration 4528/1000000: Train loss: 1.451720, Train Accuracy: 0.687500, lr = 0.000914
> Iteration 4529/1000000: Train loss: 1.535149, Train Accuracy: 0.546875, lr = 0.000914
> Iteration 4530/1000000: Train loss: 1.779923, Train Accuracy: 0.546875, lr = 0.000914
> Iteration 4531/1000000: Train loss: 1.416121, Train Accuracy: 0.687500, lr = 0.000914
> Iteration 4532/1000000: Train loss: 1.455724, Train Accuracy: 0.671875, lr = 0.000914
> Iteration 4533/1000000: Train loss: 1.455456, Train Accuracy: 0.609375, lr = 0.000914
> Iteration 4534/1000000: Train loss: 1.463598, Train Accuracy: 0.687500, lr = 0.000914
> Iteration 4535/1000000: Train loss: 1.488306, Train Accuracy: 0.656250, lr = 0.000914
> Iteration 4536/1000000: Train loss: 1.391160, Train Accuracy: 0.703125, lr = 0.000914
> Iteration 4537/1000000: Train loss: 1.542080, Train Accuracy: 0.562500, lr = 0.000914
> Iteration 4538/1000000: Train loss: 1.437874, Train Accuracy: 0.703125, lr = 0.000914
> Iteration 4539/1000000: Train loss: 1.430736, Train Accuracy: 0.703125, lr = 0.000914
> Iteration 4540/1000000: Train loss: 1.444268, Train Accuracy: 0.687500, lr = 0.000914
> Iteration 4541/1000000: Train loss: 1.452904, Train Accuracy: 0.671875, lr = 0.000914
> Iteration 4542/1000000: Train loss: 1.358010, Train Accuracy: 0.796875, lr = 0.000914
> Iteration 4543/1000000: Train loss: 1.521464, Train Accuracy: 0.593750, lr = 0.000914
> Iteration 4544/1000000: Train loss: 1.346282, Train Accuracy: 0.812500, lr = 0.000914
> Iteration 4545/1000000: Train loss: 1.414198, Train Accuracy: 0.734375, lr = 0.000914
> Iteration 4546/1000000: Train loss: 1.370777, Train Accuracy: 0.781250, lr = 0.000914
> Iteration 4547/1000000: Train loss: 1.429361, Train Accuracy: 0.687500, lr = 0.000914
> Iteration 4548/1000000: Train loss: 1.500038, Train Accuracy: 0.578125, lr = 0.000914
> Iteration 4549/1000000: Train loss: 1.387997, Train Accuracy: 0.750000, lr = 0.000914
> Iteration 4550/1000000: Train loss: 1.439233, Train Accuracy: 0.625000, lr = 0.000914
> Iteration 4551/1000000: Train loss: 1.465190, Train Accuracy: 0.671875, lr = 0.000914
> Iteration 4552/1000000: Train loss: 1.397634, Train Accuracy: 0.750000, lr = 0.000914
> Iteration 4553/1000000: Train loss: 1.378973, Train Accuracy: 0.796875, lr = 0.000914
> Iteration 4554/1000000: Train loss: 1.854280, Train Accuracy: 0.437500, lr = 0.000914
> Iteration 4555/1000000: Train loss: 1.397872, Train Accuracy: 0.765625, lr = 0.000914
> Iteration 4556/1000000: Train loss: 1.511538, Train Accuracy: 0.640625, lr = 0.000914
> Iteration 4557/1000000: Train loss: 1.526194, Train Accuracy: 0.593750, lr = 0.000914
> Iteration 4558/1000000: Train loss: 1.422717, Train Accuracy: 0.750000, lr = 0.000914
> Iteration 4559/1000000: Train loss: 1.551046, Train Accuracy: 0.515625, lr = 0.000914
> Iteration 4560/1000000: Train loss: 1.364337, Train Accuracy: 0.796875, lr = 0.000914
> Iteration 4561/1000000: Train loss: 1.463224, Train Accuracy: 0.781250, lr = 0.000914
> Iteration 4562/1000000: Train loss: 1.456426, Train Accuracy: 0.687500, lr = 0.000914
> Iteration 4563/1000000: Train loss: 1.354179, Train Accuracy: 0.765625, lr = 0.000914
> Iteration 4564/1000000: Train loss: 1.445806, Train Accuracy: 0.687500, lr = 0.000914
> Iteration 4565/1000000: Train loss: 1.444253, Train Accuracy: 0.703125, lr = 0.000914
> Iteration 4566/1000000: Train loss: 1.391588, Train Accuracy: 0.796875, lr = 0.000914
> Iteration 4567/1000000: Train loss: 1.352243, Train Accuracy: 0.828125, lr = 0.000914
> Iteration 4568/1000000: Train loss: 1.334538, Train Accuracy: 0.812500, lr = 0.000914
> Iteration 4569/1000000: Train loss: 1.400296, Train Accuracy: 0.765625, lr = 0.000914
> Iteration 4570/1000000: Train loss: 1.401171, Train Accuracy: 0.750000, lr = 0.000914
> Iteration 4571/1000000: Train loss: 1.441840, Train Accuracy: 0.640625, lr = 0.000914
> Iteration 4572/1000000: Train loss: 1.479034, Train Accuracy: 0.656250, lr = 0.000914
> Iteration 4573/1000000: Train loss: 1.410641, Train Accuracy: 0.750000, lr = 0.000914
> Iteration 4574/1000000: Train loss: 1.440084, Train Accuracy: 0.609375, lr = 0.000914
> Iteration 4575/1000000: Train loss: 1.439700, Train Accuracy: 0.687500, lr = 0.000914
> Iteration 4576/1000000: Train loss: 1.414751, Train Accuracy: 0.718750, lr = 0.000914
> Iteration 4577/1000000: Train loss: 1.396888, Train Accuracy: 0.781250, lr = 0.000914
> Iteration 4578/1000000: Train loss: 1.808508, Train Accuracy: 0.515625, lr = 0.000914
> Iteration 4579/1000000: Train loss: 1.462855, Train Accuracy: 0.656250, lr = 0.000914
> Iteration 4580/1000000: Train loss: 1.483722, Train Accuracy: 0.640625, lr = 0.000914
> Iteration 4581/1000000: Train loss: 1.464909, Train Accuracy: 0.625000, lr = 0.000914
> Iteration 4582/1000000: Train loss: 1.368422, Train Accuracy: 0.750000, lr = 0.000914
> Iteration 4583/1000000: Train loss: 1.464888, Train Accuracy: 0.687500, lr = 0.000914
> Iteration 4584/1000000: Train loss: 1.398354, Train Accuracy: 0.750000, lr = 0.000914
> Iteration 4585/1000000: Train loss: 1.509562, Train Accuracy: 0.593750, lr = 0.000914
> Iteration 4586/1000000: Train loss: 1.427382, Train Accuracy: 0.656250, lr = 0.000914
> Iteration 4587/1000000: Train loss: 1.411291, Train Accuracy: 0.703125, lr = 0.000914
> Iteration 4588/1000000: Train loss: 1.450220, Train Accuracy: 0.625000, lr = 0.000914
> Iteration 4589/1000000: Train loss: 1.427717, Train Accuracy: 0.687500, lr = 0.000914
> Iteration 4590/1000000: Train loss: 1.385659, Train Accuracy: 0.718750, lr = 0.000914
> Iteration 4591/1000000: Train loss: 1.389479, Train Accuracy: 0.765625, lr = 0.000914
> Iteration 4592/1000000: Train loss: 1.429805, Train Accuracy: 0.718750, lr = 0.000914
> Iteration 4593/1000000: Train loss: 1.401639, Train Accuracy: 0.734375, lr = 0.000914
> Iteration 4594/1000000: Train loss: 1.385487, Train Accuracy: 0.734375, lr = 0.000914
> Iteration 4595/1000000: Train loss: 1.397442, Train Accuracy: 0.718750, lr = 0.000914
> Iteration 4596/1000000: Train loss: 1.476015, Train Accuracy: 0.609375, lr = 0.000914
> Iteration 4597/1000000: Train loss: 1.389638, Train Accuracy: 0.687500, lr = 0.000914
> Iteration 4598/1000000: Train loss: 1.492611, Train Accuracy: 0.593750, lr = 0.000914
> Iteration 4599/1000000: Train loss: 1.393537, Train Accuracy: 0.765625, lr = 0.000914
> Iteration 4600/1000000: Train loss: 1.403182, Train Accuracy: 0.734375, lr = 0.000914
> Iteration 4601/1000000: Train loss: 1.413848, Train Accuracy: 0.703125, lr = 0.000914
> Iteration 4602/1000000: Train loss: 1.836226, Train Accuracy: 0.484375, lr = 0.000914
> Iteration 4603/1000000: Train loss: 1.425249, Train Accuracy: 0.703125, lr = 0.000914
> Iteration 4604/1000000: Train loss: 1.432378, Train Accuracy: 0.734375, lr = 0.000914
> Iteration 4605/1000000: Train loss: 1.412159, Train Accuracy: 0.734375, lr = 0.000914
> Iteration 4606/1000000: Train loss: 1.431850, Train Accuracy: 0.687500, lr = 0.000914
> Iteration 4607/1000000: Train loss: 1.512563, Train Accuracy: 0.593750, lr = 0.000914
> Iteration 4608/1000000: Train loss: 1.338074, Train Accuracy: 0.781250, lr = 0.000914
> Iteration 4609/1000000: Train loss: 1.428630, Train Accuracy: 0.671875, lr = 0.000914
> Iteration 4610/1000000: Train loss: 1.399022, Train Accuracy: 0.750000, lr = 0.000914
> Iteration 4611/1000000: Train loss: 1.351175, Train Accuracy: 0.781250, lr = 0.000914
> Iteration 4612/1000000: Train loss: 1.382371, Train Accuracy: 0.687500, lr = 0.000914
> Iteration 4613/1000000: Train loss: 1.375068, Train Accuracy: 0.781250, lr = 0.000914
> Iteration 4614/1000000: Train loss: 1.365613, Train Accuracy: 0.781250, lr = 0.000914
> Iteration 4615/1000000: Train loss: 1.433079, Train Accuracy: 0.734375, lr = 0.000914
> Iteration 4616/1000000: Train loss: 1.417402, Train Accuracy: 0.656250, lr = 0.000914
> Iteration 4617/1000000: Train loss: 1.388127, Train Accuracy: 0.734375, lr = 0.000914
> Iteration 4618/1000000: Train loss: 1.383092, Train Accuracy: 0.703125, lr = 0.000914
> Iteration 4619/1000000: Train loss: 1.427259, Train Accuracy: 0.734375, lr = 0.000914
> Iteration 4620/1000000: Train loss: 1.417039, Train Accuracy: 0.750000, lr = 0.000914
> Iteration 4621/1000000: Train loss: 1.519323, Train Accuracy: 0.546875, lr = 0.000914
> Iteration 4622/1000000: Train loss: 1.456779, Train Accuracy: 0.671875, lr = 0.000914
> Iteration 4623/1000000: Train loss: 1.421736, Train Accuracy: 0.718750, lr = 0.000914
> Iteration 4624/1000000: Train loss: 1.450207, Train Accuracy: 0.671875, lr = 0.000914
> Iteration 4625/1000000: Train loss: 1.401483, Train Accuracy: 0.765625, lr = 0.000914
> Iteration 4626/1000000: Train loss: 1.812582, Train Accuracy: 0.515625, lr = 0.000914
> Iteration 4627/1000000: Train loss: 1.440538, Train Accuracy: 0.671875, lr = 0.000914
> Iteration 4628/1000000: Train loss: 1.448299, Train Accuracy: 0.671875, lr = 0.000914
> Iteration 4629/1000000: Train loss: 1.409122, Train Accuracy: 0.703125, lr = 0.000914
> Iteration 4630/1000000: Train loss: 1.448029, Train Accuracy: 0.687500, lr = 0.000914
> Iteration 4631/1000000: Train loss: 1.455968, Train Accuracy: 0.640625, lr = 0.000914
> Iteration 4632/1000000: Train loss: 1.412792, Train Accuracy: 0.687500, lr = 0.000914
> Iteration 4633/1000000: Train loss: 1.388133, Train Accuracy: 0.687500, lr = 0.000914
> Iteration 4634/1000000: Train loss: 1.357973, Train Accuracy: 0.781250, lr = 0.000914
> Iteration 4635/1000000: Train loss: 1.341835, Train Accuracy: 0.796875, lr = 0.000914
> Iteration 4636/1000000: Train loss: 1.412416, Train Accuracy: 0.734375, lr = 0.000914
> Iteration 4637/1000000: Train loss: 1.390548, Train Accuracy: 0.703125, lr = 0.000914
> Iteration 4638/1000000: Train loss: 1.410559, Train Accuracy: 0.687500, lr = 0.000914
> Iteration 4639/1000000: Train loss: 1.383563, Train Accuracy: 0.734375, lr = 0.000914
> Iteration 4640/1000000: Train loss: 1.417106, Train Accuracy: 0.718750, lr = 0.000914
> Iteration 4641/1000000: Train loss: 1.448520, Train Accuracy: 0.656250, lr = 0.000914
> Iteration 4642/1000000: Train loss: 1.400305, Train Accuracy: 0.671875, lr = 0.000914
> Iteration 4643/1000000: Train loss: 1.469591, Train Accuracy: 0.578125, lr = 0.000914
> Iteration 4644/1000000: Train loss: 1.407663, Train Accuracy: 0.703125, lr = 0.000914
> Iteration 4645/1000000: Train loss: 1.421444, Train Accuracy: 0.734375, lr = 0.000914
> Iteration 4646/1000000: Train loss: 1.374548, Train Accuracy: 0.718750, lr = 0.000914
> Iteration 4647/1000000: Train loss: 1.379021, Train Accuracy: 0.734375, lr = 0.000914
> Iteration 4648/1000000: Train loss: 1.431357, Train Accuracy: 0.671875, lr = 0.000914
> Iteration 4649/1000000: Train loss: 1.439613, Train Accuracy: 0.671875, lr = 0.000914
> Iteration 4650/1000000: Train loss: 1.723072, Train Accuracy: 0.546875, lr = 0.000914
> Iteration 4651/1000000: Train loss: 1.399335, Train Accuracy: 0.718750, lr = 0.000914
> Iteration 4652/1000000: Train loss: 1.436458, Train Accuracy: 0.687500, lr = 0.000914
> Iteration 4653/1000000: Train loss: 1.368014, Train Accuracy: 0.718750, lr = 0.000914
> Iteration 4654/1000000: Train loss: 1.381723, Train Accuracy: 0.812500, lr = 0.000914
> Iteration 4655/1000000: Train loss: 1.501552, Train Accuracy: 0.593750, lr = 0.000914
> Iteration 4656/1000000: Train loss: 1.331427, Train Accuracy: 0.781250, lr = 0.000914
> Iteration 4657/1000000: Train loss: 1.471817, Train Accuracy: 0.609375, lr = 0.000914
> Iteration 4658/1000000: Train loss: 1.403450, Train Accuracy: 0.750000, lr = 0.000914
> Iteration 4659/1000000: Train loss: 1.342583, Train Accuracy: 0.828125, lr = 0.000914
> Iteration 4660/1000000: Train loss: 1.427380, Train Accuracy: 0.609375, lr = 0.000914
> Iteration 4661/1000000: Train loss: 1.299797, Train Accuracy: 0.828125, lr = 0.000914
> Iteration 4662/1000000: Train loss: 1.393541, Train Accuracy: 0.718750, lr = 0.000914

This might be a stupid question, but is the best accuracy 1.0?

**Comment by tensorfreitas** [comment] 2018-08-16 08:17
It will take a while on CPU! Yes the maximum accuracy is 1.0. But evaluate on the validation datasets (each 1000 iterations). 

Since the issue is resolved I'll close it. But feel free to reopen it if you have more questions, or just send me an email.

**Closed as completed by tensorfreitas** 2018-08-16 08:17 UTC
